project_name: hunt_showdown
games:
  arc_raiders:
    emoji: ["🚀"]
    actions:
      alarm: "📢"
      boss: "🔥"
      clear: "🧹"
      death: "☠️"
      downed: "🤬"
      elite: "👑"
      explosion: "💥"
      extract: "⛵"
      fire: "🔥"
      funny: "😂"
      damage: "⚡"
      kill: "💀"
      multi_kill: "🎆"
      perfect: "💫"
      yeet: "🌀"
      rare_loot: "💎"
      revive: "❤️"
      run_end: "⏹️"
      run_start: "▶️"
      stealth: "🕵️"
      team_wipe: "💣"
  hunt_showdown:
    emoji: ["🤠"]
    actions:
      run_start: "▶️"
      run_end: "⏹️"
      alert: "🔔"
      ammo: "💣"
      assist: "🤝"
      banish: "👹"
      bleed: "🩸"
      clear: "🧹"
      death: "☠️"
      downed: "🤬"
      extract: "⛵"
      fire: "🔥"
      funny: "😂"
      headshot: "🤯"
      heal: "🩹"
      kill: "💀"
      melee: "🗡️"
      noise: "📢"
      poison: "☠️"
      reload: "🔄"
      revive: "❤️"
      shootout: "🔫"
      snipe: "🎯"
      stealth: "🕵️"
      traded: "🔄"
      trap: "🪤"
  enshrouded:
    emoji: ["🧙", "🪄"]
    actions:
      clear: "🧹"
      death: "☠️"
      fire: "🔥"
      drowned: "🤽"
      fish: "🐟"
      kill: "💀"
      mining: "⛏️"
      magic: "🧝"
      revive: "✨"
      teleport: "🌀"
  chivalry2:
    emoji: ["🤺"]
    actions:
      clear: "🧹"
      death: "🩸"
      kill: "☠️"
  fortnite:
    emoji: ["🍆"]
    actions:
      clear: "🧹"
      death: "☠️"
      kill: "💀"
      run_end: "⏹️"
      run_start: "▶️"
  hell_divers_2:
    emoji: ["🪖"]
    actions:
      run_end: "⏹️"
      run_start: "▶️"
      clear: "🧹"
      death: "☠️"
      kill: "💀"
      bots: "🤖"
      squids: "🦑"
      extract: "🐦"
      terminids: "🪲"
      veterans: "🎖️"
      rookies: "👶"

