project_name: hunt_showdown
games:
  hunt_showdown:
    emoji: ["🤠"]
    actions:
      alert: "🔔"
      ammo: "💣"
      assist: "🤝"
      banish: "👹"
      bleed: "🩸"
      death: "☠️"
      downed: "🤬"
      extract: "⛵"
      fire: "🔥"
      funny: "😂"
      headshot: "🤯"
      heal: "🩹"
      kill: "💀"
      melee: "🗡️"
      noise: "📢"
      poison: "☠️"
      reload: "🔄"
      revive: "❤️"
      shootout: "🔫"
      snipe: "🎯"
      stealth: "🕵️"
      traded: "🔄"
      trap: "🪤"
  enshrouded:
    emoji: ["🧙", "🪄"]
    actions:
      death: "☠️"
      fire: "🔥"
      drowned: "🤽"
      fish: "🐟"
      kill: "💀"
      mining: "⛏️"
      magic: "🧝"
      revive: "✨"
      teleport: "🌀"
  chivalry2:
    emoji: ["🤺"]
    actions:
      death: "🩸"
      kill: "☠️"
  fortnite:
    emoji: ["🍆"]
    actions:
      death: "☠️"
      kill: "💀"
  hell_divers_2:
    emoji: ["🪖"]
    actions:
      death: "☠️"
      kill: "💀"
      bots: "🤖"
      squids: "🦑"
      extract: "🐦"
      terminids: "🪲"
      veterans: "🎖️"
      rookies: "👶"
